-- Your SQL goes here

ALTER TYPE OBJECT_STATUS ADD VALUE 'FINALIZING';
CREATE TYPE ENDPOINT_STATUS AS ENUM ('INITIALIZING', 'AVAILABLE', 'DEGRADED', 'UNAVAILABLE', 'MAINTENANCE');
ALTER TABLE endpoints ADD COLUMN status ENDPOINT_STATUS NOT NULL DEFAULT 'AVAILABLE';
ALTER TABLE users ADD COLUMN is_service_account BOOL NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN email VARCHAR(511) DEFAULT '';

ALTER TABLE api_tokens ADD COLUMN used_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE api_tokens ADD COLUMN is_session BOOL NOT NULL DEFAULT FALSE;